<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Task_Manager.Services</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Task Manager.Domain\TaskManager.Domain.csproj" />
    <ProjectReference Include="..\Task Manager.DTOs\TaskManager.DTOs.csproj" />
    <ProjectReference Include="..\Task Manager.Infrastructure\TaskManager.Infrastructure.csproj" />
  </ItemGroup>

</Project>
